import { chromium } from './node_modules/playwright/index.mjs';
const browser = await chromium.launch();
const page = await browser.newPage();
await page.setViewportSize({ width: 393, height: 852 });
await page.goto('http://localhost:3333');
await page.evaluate(() => document.documentElement.setAttribute('data-theme', 'dark'));
await page.waitForTimeout(2500);
await page.screenshot({ path: './full_page.png', fullPage: true });
await browser.close();
console.log('done');
